# **This is a credit dataset for bank** 
Ogunkeyede Folake Assignment

In [14]:
#import libraries needed for analysis the data
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

reading the dataset

In [5]:
data = pd.read_csv("../input/dataset-yemsquare/german_credit_data.csv")

Dsplay the datset

In [6]:
data.head()

Clearing up the dataset by removing unwanted columns

In [7]:
data.drop(data.columns[0], inplace=True, axis=1)
print("Database has {} obserwations (customers) and {} columns (attributes).".format(data.shape[0],data.shape[1]))
print("Missing values in each column:\n{}".format(data.isnull().sum()))
print("Columns data types:\n{}".format(data.dtypes))

Displaying the unique dataset

In [8]:
n_unique = data.nunique()
print("Number of unique values:\n{}".format(n_unique))

Display the unique values in each unique coulumn

In [9]:
print("Unique values in each categorical column:")
for col in data.select_dtypes(include=[object]):
    print(col,":", data[col].unique())

Representing the data in graph using scatter plot by using standardscalar library

In [11]:
def scatters(data, h=None, pal=None):
    fig, (ax1, ax2, ax3) = plt.subplots(3,1, figsize=(8,8))
    sns.scatterplot(x="Credit amount",y="Duration", hue=h, palette=pal, data=data, ax=ax1)
    sns.scatterplot(x="Age",y="Credit amount", hue=h, palette=pal, data=data, ax=ax2)
    sns.scatterplot(x="Age",y="Duration", hue=h, palette=pal, data=data, ax=ax3)
    plt.tight_layout()

Displaying the graphs

In [15]:
scatters(data, h="Sex")